### ISSUE TITLE
Feature Request: Undo functionality and right click tab menu access

### ISSUE THREAD

**Issue by Bamajon1974** [Zegnat/browserext-window-merger#8] opened 2020-03-03 17:04 UTC
Is it possible to implement the ability to right click a tab in the tab bar to access the functionality of the extension? Perhaps set an option to right click a page or right click a tab in the tab bar to access the extension?

Also, is it possible to implement an undo merge function?

**Comment by Zegnat** [comment] 2020-03-05 07:58
> Is it possible to implement the ability to right click a tab in the tab bar to access the functionality of the extension?

It should be, I just almost never right click up there. I can probably enable that without any problems.

> Perhaps set an option to right click a page or right click a tab in the tab bar to access the extension?

I would love to offer options, but that may be a little further off. This extension is compatible with a version of Firefox old enough that it does not support the `options_ui` feature for embedding a preferences view.

So either it will be something only visible in newer browsers, or I have to find an alternative way of triggering access to the view.

> Also, is it possible to implement an undo merge function? 

This is less likely to happen, because of the many edge cases. I have thought about it though. It has happened that I realised I messed up after clicking “Merge all …”. But what do I do if someone has chosen to move a tab within its new window? Pull it out or keep it at its new place? What about if you have navigated somewhere within a tab?

It also did not seem feasible to timebox it to only be able to undo for a few seconds, at least in my personal testing it became very unintuitive.

If you have any ideas on how you imagine this working, let me know!

**Comment by Bamajon1974** [comment] 2020-03-05 15:57
Thank you for the reply. 

Since Firefox allows right-click functionality to be implemented in the tab context menus, I think it would be better to move this extension right-click operation to the tab menu rather than the page menu. The right-click page menu gets cluttered enough from other extension. 

I think newer web extensions in Firefox allow options to add right click functionality to the page and/or tab. For some reason Chrome doesn't allow tab context menus. But given that Mozilla really wants to get away from pre-quantum releases, would it be better to update the extension for full quantum compatibility? 

I am not really sure how to implement a full-proof undo merge functionality. I am not a coder so I don't really know much about the nuts and bolts of how these extensions work. I was thinking along the lines of, after merging windows, the undo would return to just the previous state reopening multiple windows and placing the tabs back where they were, and leave it at that. 

Alternatively, would it be better to introduce an inverse merge feature, like split, that would send tabs from one window into different windows opened? It seems like this split functionality would be redundant with some other extensions though. What do you think?

Thanks in advance!

**Comment by Zegnat** [comment] 2020-03-05 18:43
> Since Firefox allows right-click functionality to be implemented in the tab context menus, I think it would be better to move this extension right-click operation to the tab menu rather than the page menu. The right-click page menu gets cluttered enough from other extension.

I myself almost never have my cursor up there. Which means that I will probably never take away the option from the context menu on pages. But I am totally willing to add it to the tab bar in addition to the page.

I will also be looking into providing an option to disable the menu within the page context menu, but as I said, that might be dependent on whether I can do it without breaking backwards compatibility.

> I am not really sure how to implement a full-proof undo merge functionality. I am not a coder so I don't really know much about the nuts and bolts of how these extensions work. I was thinking along the lines of, after merging windows, the undo would return to just the previous state reopening multiple windows and placing the tabs back where they were, and leave it at that.

It is not really about the code, it is about the edge-cases and the user experience.

What if I merge all my windows, and then go into some tabs, move those around (maybe even split into a new window), navigate some pages, and after that click on undo because it turns out I merged a window more than I wanted to. Exactly how much do you now undo? What do you do with the changed tabs?

I can’t really grasp a simple and intuitive way of offering an undo. I feel like as soon as I offer an undo option people will find ways to break it, or find behaviours that are unexpected.

**Comment by Zegnat** [comment] 2020-03-14 22:14
As you can see in the latest version of the README there is now an option to choose where the context menu shows up. This is not yet released as an update on AMO because more testing is needed to make sure I did not break something else on the way. I also have not yet had the time to test older supported browsers (like ESR).

If you want to help test this you can run the extension from source. If you do not know how to do this it is probably best to wait for the next release. I hope to get that one pushed during the upcoming week.

Thanks for your interest!

![Screenshot: Window Merger preferences pane.](https://raw.githubusercontent.com/Zegnat/browserext-window-merger/d3b65bf1d085b98d19c58773a3ef8474a564a65a/assets/preferences.png)

**Comment by Bamajon1974** [comment] 2020-03-16 14:51
Great! Thank you for implementing the changes!

Since the new extension has not been uploaded yet, I am not sure how to
manually install the extension from GitHub. Does it need to be compiled
first? If compiling is not necessary, I am guessing I install the extension
from a file in the manage extensions settings, correct? Do I need to
download the entire repository from Github? Do I need to unzip?

Thanks, Jon

**Comment by Zegnat** [comment] 2020-03-17 17:21
> I am not sure how to manually install the extension from GitHub. Does it need to be compiled first? If compiling is not necessary, I am guessing I install the extension from a file in the manage extensions settings, correct? Do I need to download the entire repository from Github?

If you haven’t run unpackaged addons before I would probably recommend waiting for the real release.

If you do want to play with it, Mozilla has an article on [temporary add-on installation](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/). You’ll probably end up going through `about:debugging`. Not sure whether you can load a zip or whether you would need all of the files unzipped in a directory. I have them unpacked while developing, for obvious reasons.

I will not really be able to assist with that though. I am still hoping to find enough time to test things myself and get a fully packaged release out on AMO by the end of the week.

**Comment by Bamajon1974** [comment] 2020-03-17 21:01
That's fine. I can wait until the extension is uploaded into AMO.

Thanks, Jon

**Comment by Zegnat** [comment] 2020-03-22 13:17
The v0.5.0 release is now available both [here on GitHub](https://github.com/Zegnat/browserext-window-merger/releases/tag/v0.5.0) and [on AMO](https://addons.mozilla.org/firefox/addon/window-merger/).

I am closing this ticket, and have created a separate ticket for further thinking about an undo option. Thank you very much for your interest!

**Comment by Bamajon1974** [comment] 2020-03-31 23:11
I finally got to installing the new version of the extension and the
options to merge do not show up on the right click menu or tab menu. I
tried restarting the browser with no luck. Any ideas what I should try? I
noticed that there is no save button when you change an option. I assume
the changes are saved automatically?
Thanks, Jon

**Comment by Zegnat** [comment] 2020-04-01 07:03
Reopening for troubleshooting.

You are right, there is not supposed to be any save button. Preferences should apply immediately. And if you open the preference screen in multiple tabs all those should stay in sync. I took some extra time to make sure that experience would be as smooth as possible.

You should be able to notice the preferences getting saved if you restarted the browser, as it should have kept whatever you changed it to.

What version of Firefox are you using? I have tried to be thorough in my testing and checked with both the latest ESR release and latest stable release (74.0 at time of writing). Both seem to work for me.

I have attached a screencast of me using the preferences and the menu showing up when right clicking on the tab bar below.

![Screencast: changing the context menu location.](https://user-images.githubusercontent.com/490579/78107871-893f5680-73f6-11ea-9a28-60a596919e4b.gif)

One thing that might be important to note is that you must right click and actual existing tab. Because of limitations in Firefox extension options, I cannot add a context menu to the entire tab strip. (You can see the different options I have [on this MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType).)

![Screencast: the context menu only shows up when right clicking a tab.](https://user-images.githubusercontent.com/490579/78108360-82651380-73f7-11ea-9e77-2f7dfb5b246b.gif)

If you are still having problems, please let me know your version of Firefox so I can try to reproduce the problem!

**Comment by Bamajon1974** [comment] 2020-04-01 11:58
Hi Martijn

I am using Firefox v74 on both my work and home computer and can confirm
that the right-click options do not appear on either browser after
installation of the extension. I even disabled all of the other running
add-ons and still no luck.

Any suggestions on what else I could do?

Thanks, Jon

**Comment by Zegnat** [comment] 2020-04-01 12:11
The screencasts above were made in Firefox 74.0, today, so it is very strange if you are seeing a different behaviour.

> _[…]_ can confirm that the right-click options do not appear on either browser after installation of the extension.

You may have to create a new window directly after installation to trigger it running for the first time, as it only runs on focus changes. Though I am not a 100% sure of that.

Do you get the menu neither on the tab bar nor on normal webpages when you right click? You were able to use the add-on before this update, right?

The only other thing I can think of is that you go to `about:debugging#/runtime/this-firefox`, find Window Merger, and click on the “Inspect” button. This will open the browser console for extensions. Make sure to be on the “Console” tab and try using the extension to see if you get any errors.

I have not been able to get any erros myself so far.

**Comment by Bamajon1974** [comment] 2020-04-01 12:48
Ok the menus show up when a second windows is open. The second open window
definitely triggers the extension now. I feel a little dumb! Sorry about
that !

**Comment by Zegnat** [comment] 2020-04-01 12:52
If you didn’t have a second window at all, it was never going to show, that is true!

I will investigate later whether it actually checks all the windows upon installation. As I am not sure about that. But will close this ticket again. Let me know how things go and feel free to open further tickets if you run into trouble!

(And I always appreciate [reviews on AMO](https://addons.mozilla.org/en-GB/firefox/addon/window-merger/reviews/), just sayin’ 😉 )

**Closed by Zegnat** 2020-04-01 12:52 UTC
Labels: research
